#!/bin/sh

if [ -z "$TEQUILA" ]; then
    echo "You have to use tequila, not directly this script."
    exit 1
fi

if [ -z "$SERVER_NAME" ] || [ -z "$SERVER_USER" ]; then
    echo "Missing SERVER_NAME and SERVER_USER variables"
    exit 1
fi

server_start() {
    export JAVA_OPTS="$JAVA_OPTS $(cat "$TEQUILA_JVM_OPTS" | sed -E 'N; s/[ \n\r\t]+/ /g')"
    export SERVER_OPTS="$SERVER_OPTS $(cat "$TEQUILA_APP_OPTS" | sed -E 'N; s/[ \n\r\t]+/ /g')"
    screen -dmS "$SERVER_NAME" su "$SERVER_USER" -c \"java $JAVA_OPTS -jar server.jar $SERVER_OPTS\"
}

getpid() {
    screen -ls | grep -E "[0-9]+.$SERVER_NAME" | cut -f2 | cut -d. -f1
}

server_stop() {
    pid=$(getpid)
    server_send stop
    wait $pid
}

server_send() {
    screen -S "$SERVER_NAME" -p 0 -X stuff "$@$(printf '\r')"
}

main() {
    cmd=$1; shift
    server_$cmd $@
}

main $@